/* Реальные названия авто в автосалонах */
const RealCarNames = {
  /* Добавляете сюда свои авто, по примеру: */
  /* "название_veh": "Реальное название которое будет показано" */

  //middle
  "asbo": "Maxwell Asbo",
  "asea": "Declasse Asea",
  "bfinjection": "BF Injection",
  "bifta": "BF Bifta",
  "blade": "Vapid Blade",
  "blista": "Dinka Blista",
  "blista2": "Dinka Blista Compact",
  "blista3": "Go Go Monkey Blista",
  "brioso": "Grotti Brioso R/A",
  "brioso2": "Grotti Brioso 300",
  "buccaneer": "Albany Buccaneer",
  "buccaneer2": "Albany Buccaneer Custom",
  "buffalo": "Bravado Buffalo",
  "cavalcade": "Albany Cavalcade",
  "cheburek": "RUNE Cheburek",
  "chino": "Vapid Chino",
  "chino2": "Vapid Chino Custom",
  "club": "BF Club",
  "dilettante": "Karin Dilettante",
  "dukes": "Imponte Dukes",
  "dynasty": "Weeny Dynasty",
  "ellie": "Vapid Ellie",
  "emperor": "Albany Emperor",
  "emperor2": "Albany Emperor Rusted",
  "faction": "Willard Faction",
  "faction2": "Willard Faction Custom",
  "fagaloa": "Vulcar Fagaloa",
  "felon": "Lampadati Felon",
  "fugitive": "Cheval Fugitive",
  "futo": "Karin Futo",
  "futo2": "Karin Futo GTX",
  "gauntlet": "Bravado Gauntlet",
  "gauntlet3": "Bravado Gauntlet Classic",
  "glendale": "Benefactor Glendale",
  "glendale2": "Benefactor Glendale V2",
  "habanero": "Emperor Habanero",
  "hellion": "Annis Hellion",
  "impaler": "Declasse Impaler",
  "ingot": "Vulcar Ingot",
  "intruder": "Karin Intruder",
  "issi3": "Weeny Apocalypse Issi",
  "kanjo": "Dinka Blista Kanjo Compact",
  "landstalker": "Dundreary Landstalker",
  "landstalker2": "Dundreary Landstalker XL",
  "manana": "Albany Manana Cabrio",
  "manana2": "Albany Manana",
  "mesa": "Canis Mesa",
  "michelli": "Lampadati Michelli GT",
  "minivan": "Vapid Minivan",
  "nebula": "Vulcar Nebula Turbo",
  "oracle": "Übermacht Oracle",
  "panto": "Benefactor Panto",
  "patriot": "Mammoth Patriot",
  "peyote": "Vapid Peyote Cabrio",
  "peyote3": "Vapid Peyote",
  "phoenix": "Imponte Phoenix",
  "picador": "Cheval Picador",
  "pigalle": "Lampadati Pigalle",
  "prairie": "Bollokan Prairie",
  "premier": "DeClasse Premier",
  "primo": "Albany Primo",
  "radi": "Vapid Radius",
  "rancherxl": "Declasse Rancher XL",
  "rebel": "Karin Rebel",
  "regina": "Dundreary Regina",
  "retinue2": "Vapid Retinue MkII",
  "rhapsody": "DeClasse Rhapsody",
  "seminole2": "Canis Seminole Frontier",
  "slamvan2": "Vapid Lost Slamvan",
  "stalion": "Declasse Stallion ",
  "stanier": "Vapid Stanier",
  "stratum": "Zirconium Stratum",
  "surfer2": "BF Surfer Rusted",
  "surfer": "BF Surfer",
  "tampa": "Declasse Tampa",
  "tornado": "Declasse Tornado",
  "tornado2": "Declasse Tornado Cabrio",
  "tornado3": "Declasse Tornado Rusted",
  "tornado4": "Declasse Tornado Rusted Cabrio",
  "tornado5": "Declasse Tornado Custom",
  "vamos": "Declasse Vamos",
  "virgo2": "Dundreary Virgo Classic Custom",
  "voodoo": "Declasse Voodoo",
  "voodoo2": "Declasse Voodoo Rusted",
  "washington": "Albany Washington",
  "weevil": "BF Weevil",

  //standart
  "asterope": "Karin Asterope",
  "baller": "Gallivanter Baller First Gen",
  "baller2": "Gallivanter Baller Second Gen",
  "baller3": "Gallivanter Baller LE",
  "bjxl": "Karin BeeJay XL",
  "brawler": "Coil Brawler",
  "buffalo2": "Bravado Buffalo S",
  "calico": "Karin Calico GTF",
  "cavalcade2": "Albany Cavalcade Second Gen",
  "clique": "Vapid Clique",
  "cog55": "Enus Cognoscenti 55",
  "cogcabrio": "Enus Cognoscenti Cabrio",
  "dominator": "Vapid Dominator",
  "elegy": "Annis Elegy RH8",
  "elegy2": "Annis Elegy Retro Custom",
  "euros": "Annus Euros",
  "exemplar": "Dewbauchee Exemplar",
  "felon2": "Lampadati Felon GT",
  "fq2": "Fathom FQ 2",
  "freecrawler": "Canis Freecrawler",
  "fusilade": "Schyster Fusilade",
  "gauntlet4": "Bravado Gauntlet Hellfire",
  "gauntlet5": "Bravado Gauntlet Classic Custom",
  "granger": "Declasse Granger",
  "gresley": "Bravado Gresley",
  "hermes": "Albany Hermes",
  "hustler": "Vapid Hustler",
  "imperator": "Vapid Imperator",
  "issi2": "Weeny Issi",
  "jackal": "Ocelot Jackal",
  "komoda": "Lampadati Komoda",
  "kuruma": "Karin Kuruma",
  "massacro": "Dewbauchee Massacro",
  "nightshade": "Imponte Nightshade",
  "novak": "Lampadati Novak",
  "oracle2": "Übermacht Oracle",
  "penumbra": "Maibatsu Penumbra",
  "penumbra2": "Maibatsu Penumbra FF",
  "previon": "Karin Previon",
  "rapidgt3": "Dewbauchee Rapid GT Classic",
  "remus": "Annis Remus",
  "retinue": "Vapid Retinue",
  "rocoto": "Obey Rocoto",
  "rt3000": "Dinka RT3000",
  "ruiner": "Imponte Ruiner",
  "sabregt": "Declasse Sabre Turbo",
  "sabregt2": "Declasse Sabre Turbo Custom",
  "savestra": "Annis Savestra",
  "schafter2": "Benefactor Schafter",
  "schwarzer": "Benefactor Schwarzer",
  "seminole": "Canis Seminole",
  "sentinel2": "Übermacht Sentinel",
  "sentinel3": "Übermacht Sentinel Classic",
  "serrano": "Benefactor Serrano",
  "sultan2": "Karin Sultan Classic",
  "sultan": "Karin Sultan",
  "sultan3": "Karin Sultan RS Classic",
  "surge": "Cheval Surge",
  "tailgater": "Obey Tailgater",
  "tropos": "Lampadati Tropos",
  "tulip": "Declasse Tulip",
  "vigero": "Declasse Vigero",
  "virgo": "Albany Virgo",
  "viseris": "Lampadati Viseris",
  "warrener": "Vulcar Warrener",
  "windsor": "Enus Windsor",
  "xls": "Benefactor XLS",
  "yosemite": "Declasse Yosemite",
  "zion3": "Übermacht Zion Classic",
  "zr350": "Annis ZR350",

  //premium
  "baller4" : "Gallivanter Baller LE LWB",
  "sc1" : "Übermacht SC1",
  "specter" : "Dewbauchee Specter",
  "alpha" : "Albany Alpha",
  "tailgater2" : "Obey Tailgater S",
  "cognoscenti" : "Enus Cognoscenti",
  "revolter" : "Übermacht Revolter",
  "sugoi" : "Dinka Sugoi",
  "seven70" : "Dewbauchee Seven-70",
  "dominator3" : "Vapid Dominator GTX",
  "casco" : "Lampadati Casco",
  "hotknife" : "Vapid Hotknife",
  "rapidgt" : "Dewbauchee Rapid GT",
  "schafter4" : "Benefactor Schafter LWB",
  "voltic" : "Coil Voltic",
  "zion2" : "Übermacht Zion Cabrio",
  "cypher" : "Übermacht Cypher",
  "khamelion" : "Hijak Khamelion",
  "surano" : "Benefactor Surano",
  "drafter" : "Obey 8F Drafter",
  "jester3" : "Dinka Jester Classic",
  "lynx" : "Ocelot Lynx",
  "rapidgt2" : "Dewbauchee Rapid GT",
  "schafter3" : "Benefactor Schafter V12",
  "dominator7" : "Vapid Dominator ASP",
  "imorgon" : "Overflod Imorgon",
  "feltzer2" : "Benefactor Feltzer",
  "jester4" : "Dinka Jester",
  "vstr" : "Albany V-STR",
  "ninef2" : "Obey 9F Cabrio",
  "pariah" : "Ocelot Pariah",
  "rebla" : "Übermacht Rebla GTS",
  "dubsta" : "Benefactor Dubsta",
  "dubsta2" : "Benefactor Dubsta Second Gen",
  "jugular" : "Ocelot Jugular",
  "neon" : "Pfister Neon",
  "streiter" : "Benefactor Streiter",
  "vectre" : "Emperor Vectre",
  "huntley" : "Enus Huntley S",
  "paragon" : "Enus Paragon R",
  "patriot2" : "Mammoth Patriot Stretch",
  "verlierer2" : "Bravado Verlierer",
  "turismo2" : "Grotti Turismo Classic",
  "vacca" : "Pegassi Vaca",
  "windsor2" : "Enus Windsor Drop",
  "schlagen" : "Benefactor Schlagen GT",
  "stretch" : "Dundreary Stretch",
  "raiden" : "Coil Raiden",
  "italigto" : "Grotti Itali GTO",
  "neo" : "Vysser Neo",
  "superd" : "Enus Super Diamond",
  "toros" : "Pegassi Toros",
  "jb7002" : "Dewbauchee JB 700W",
  "stinger" : "Grotti Stinger",
  "swinger" : "Ocelot Swinger",
  "tempesta" : "Pegassi Tempesta",
  "thrax" : "Truffade Thrax",
  "torero" : "Pegassi Torero",
  "btype" : "Albany Roosevelt",
  "dubsta3" : "Benefactor Dubsta 6x6",
  "btype3" : "Albany Roosevelt Valor",
  "btype2" : "Albany Fränken Stange",
  "stafford" : "Enus Stafford",

  //sport
  "adder": "Truffade Adder",
  "autarch": "Overflod Autarch",
  "banshee": "Bravado Banshee",
  "banshee2": "Bravado Banshee 900R",
  "bestiagts": "Grotti Bestia GTS",
  "bullet": "Vapid Bullet",
  "carbonizzare": "Grotti Carbonizzare",
  "cheetah": "Grotti Cheetah",
  "cheetah2": "Grotti Cheetah Classic",
  "comet2": "Pfister Comet",
  "comet3": "Pfister Comet Retro Custom",
  "comet4": "Pfister Comet Safari",
  "comet5": "Pfister Comet SR",
  "comet6": "Pfister Comet S2",
  "coquette": "Invetero Coquette",
  "coquette2": "Invetero Coquette Classic",
  "coquette3": "Invetero Coquette BlackFin",
  "coquette4": "Invetero Coquette D10",
  "cyclone": "Coil Cyclone",
  "deveste": "Principe Deveste Eight",
  "deviant": "Schyster Deviant",
  "emerus": "Progen Emerus",
  "entity2": "Överflöd Entity XXR",
  "entityxf": "Överflöd Entity XF",
  "f620": "Ocelot F620",
  "feltzer3": "Benefactor Stirling GT",
  "fmj": "Vapid FMJ",
  "furia": "Grotti Furia",
  "furoregt": "Lampadati Furore GT",
  "gp1": "Progen GP1",
  "growler": "Pfister Growler",
  "gt500": "Grotti GT500",
  "infernus": "Pegassi Infernus",
  "infernus2": "Pegassi Infernus Classic",
  "issi7": "Weeny Issi Sport",
  "italigtb": "Progen Itali GTB",
  "italirsx": "Grotti Itali RSX",
  "jester": "Dinka Jester",
  "krieger": "Benefactor Krieger",
  "locust": "Ocelot Locust",
  "mamba": "Declasse Mamba",
  "monroe": "Pegassi Monroe",
  "nero": "Truffade Nero",
  "ninef": "Obey 9F",
  "omnis": "Obey Omnis",
  "osiris": "Pegassi Osiris",
  "penetrator": "Ocelot Penetrator",
  "pfister811": "Pfister 811",
  "prototipo": "Grotti X80 Proto",
  "reaper": "Pegassi Reaper",
  "ruston": "Hijak Ruston",
  "stingergt": "Grotti Stinger GT",
  "t20": "Progen T20",
  "taipan": "Cheval Taipan",
  "tezeract": "Pegassi Tezeract",
  "tigon": "Lampadati Tigon",
  "turismor": "Grotti Turismo R",
  "tyrant": "Overflod Tyrant",
  "tyrus": "Progen Tyrus",
  "vagner": "Dewbauchee Vagner",
  "visione": "Grotti Visione",
  "xa21": "Ocelot XA-21",
  "zorrusso": "Pegassi Zorrusso",
  "ztype": "Truffade Z-Type",
  "zentorno": "Pegassi Zentorno",

  //грузовые
  "bison": "Bravado Bison",
  "bobcatxl": "Vapid Bobcat XL",
  "bodhi2": "Canis Bodhi",
  "brutus": "Declasse Apocalypse Brutus",
  "burrito3": "Declasse Burrito",
  "caracara2": "Vapid Caracara 4x4",
  "contender": "Vapid Contender",
  "dloader": "Bravado Duneloader",
  "everon": "Karin Everon",
  "gburrito2": "Declasse Burrito Custom",
  "kamacho": "Canis Kamacho",
  "moonbeam": "Declasse Moonbeam",
  "ratloader2": "Bravado Rat-Truck",
  "rebel2": "Karin Rebel",
  "riata": "Vapid Riata",
  "sandking": "Vapid Sandking XL",
  "sandking2": "Vapid Sandking SWB",
  "slamvan": "Vapid Slamvan",
  "slamvan3": "Vapid Slamvan Custom",
  "speedo": "Vapid Speedo Custom",
  "speedo4": "Vapid Speedo",
  "yosemite": "Declasse Yosemite",
  "yosemite3": "Declasse Yosemite Rancher",
  "youga2": "Bravado Youga Classic",


  //moto
  "akuma": "Dinka Akuma",
  "avarus": "LCC Avarus",
  "bagger": "Western Motorcycle Company Bagger",
  "bati": "Pegassi Bati 801",
  "bf400": "Nagasaki BF400",
  "blazer": "Nagasaki Blazer",
  "blazer3": "Nagasaki Hot Rod Blazer",
  "blazer4": "Nagasaki Street Blazer",
  "carbonrs": "Nagasaki Carbon RS",
  "cliffhanger": "cliffhanger",
  "daemon": "Western Motorcycle Company Cliffhanger",
  "daemon2": "Western Motorcycle Company Daemon",
  "deathbike": "Western Motorcycle Company Apocalypse Deathbike",
  "deathbike2": "Western Motorcycle Company Future Shock Deathbike",
  "deathbike3": "Western Motorcycle Company Nightmare Deathbike",
  "defiler": "Shitzu Defiler",
  "diablous": "Principe Diabolus",
  "diablous2": "Principe Diabolus Custom",
  "double": "Dinka Double-T",
  "enduro": "Dinka Enduro",
  "esskey": "Pegassi Esskey",
  "faggio": "Pegassi Faggio Sport",
  "faggio2": "Principe Faggio",
  "faggio3": "Pegassi Faggio Mod",
  "fcr": "Pegassi FCR 1000",
  "fcr2": "Pegassi FCR 1000 Custom",
  "gargoyle": "Western Motorcycle Company Gargoyle",
  "hakuchou": "Shitzu Hakuchou",
  "hakuchou2": "Shitzu Hakuchou Drag",
  "hexer": "Liberty City Cycles Hexer",
  "innovation": "Liberty City Cycles Innovation",
  "manchez": "Maibatsu Manchez",
  "manchez2": "Maibatsu Manchez Scout",
  "nemesis": "Principe Nemesis",
  "nightblade": "Western Nightblade",
  "pcj": "Shitzu PCJ-600",
  "ruffian": "Pegassi Ruffian",
  "sanchez2": "Maibatsu Sanchez",
  "sanctus": "LCC Sanctus",
  "shotaro": "Nagasaki Shotaro",
  "sovereign": "Western Motorcycle Company Sovereign",
  "stryder": "Nagasaki Stryder",
  "thrust": "Dinka Thrust",
  "vader": "Shitzu Vader",
  "verus": "Dinka Verus",
  "vortex": "Pegassi Vortex",
  "wolfsbane": "Western Wolfsbane",
  "zombiea": "Western Zombie Bobber",
  "zombieb": "Western Zombie Chopper",


// aero room
  "Buzzard2": "Nagasaki Buzzard",
  "Mammatus": "JoBuilt Mammatus",
  "Luxor2": "Buckingham Luxor Deluxe",

// авто-донат
  "apriora" : "Lada Priora",
  "ae86" : "Toyota Corolla AE86",
  "jesko" : "Koenigsegg Jesko",
  "a9" : "Audi A9",
  "aetron" : "Audi e‑tron S",
  "agera11" : "Koenigsegg Agera",
  "audia6" : "Audi A6",
  "audia8" : "Audi A8",
  "bcr1drag" : "Yamaha YZF-R1",
  "bmwe38" :"BMW E38",
  "bmwg20" : "BMW 3-Series G20",
  "bmwm7" : "BMW M760Li",
  "bmwx7" : "BMW X7",
  "bnr32" : "Nissan Skyline R32",
  "bnr34" : "Nissan Skyline R34",
  "boss302" : "Ford Mustang Boss 302",
  "c63coupe" : "Mercedes-AMG C63",
  "camry18" : "Toyota Camry",
  "chevelle1970" : "Chevrolet Chevelle SS 454",
  "countach" : "Lamborghini Countach LPI 800-4",
  "durango18" : "Dodge Durango SRT Hellcat HPE1000",
  "evoque" : "Range Rover Evoque",
  "explorer" : "Ford Explorer",
  "f8spider" : "Ferrari F8 Spider",
  "freshaudi" : "Audi RS 6 Avant",
  "g63amg6x6" : "Mercedes-AMG G 63 6x6",
  "g65fresh" : "Mercedes-Benz 65 AMG",
  "gcmsentra20" : "Nissan Bluebird Sylphy",
  "glc2021" : "Mercedes-Benz GLC 300 4MATIC",
  "gle63" : "Mercedes-AMG GLE 63 S",
  "gls600" : "Mercedes-Maybach GLS 600",
  "hevo" : "Lamborghini Huracan GT3 EVO",
  "huracan" : "Lamborghini Huracan",
  "kiastinger" : "KIA Stinger",
  "lc200" : "Toyota Land Cruiser 200",
  "lrdef17" : "Land Rover Defender 110",
  "m3e46" : "BMW M3 E46",
  "m4comp" : "BMW M4 Competition",
  "m5f90" : "BMW M5 F90",
  "mbgls63" : "Mercedes-Benz AMG GLS 63",
  "mcls53" : "BRABUS 500 Mercedes-AMG CLS 53",
  "mere63amg" : "Mercedes-Benz AMG E 63 S",
  "ocnetrongt" : "Audi e-tron GT",
  "optima" : "Kia Optima SXL Turbo",
  "p1" : "McLaren P1",
  "porsche2021" : "Porsche 911 Turbo S",
  "rmod240sx" : "Nissan 240sx by Rocket Bunny",
  "rmodatlantic" : "Bugatti Atlantic",
  "rmodbacalar" : "Bentley Mulliner Bacalar",
  "rmodbentleygt" : "Bentley Continental GT Speed",
  "rmodbiposto" : "Abarth 595 Competizione",
  "rmodbugatti" : "Bugatti La Voiture Noire",
  "rmodcharger69" : "Dodge Charger 1969",
  "rmodchiron300" : "Bugatti Chiron Super Sport 300+",
  "rmode63s" : "Brabus 800 Mercedes-AMG E63 S6",
  "rmodessenza" : "Lamborghini Essenza SCV12",
  "rmodg65" : "Mercedes-Benz G65 AMG",
  "rmodgt63" : "BRABUS 800 Mercedes-AMG GT 63 S",
  "rmodi8ks" : "BMW i8 Coupe K.S. Edition",
  "rmodjeep" : "Jeep Grand Cherokee Trackhawk",
  "rmodm5e34" : "BMW M5 e34",
  "rmodm8c" : "BMW M8 Competition Cabrio",
  "rmodrover" : "Range Rover Sport SVR by Mansory",
  "rmodsuprapandem" : "Toyota Supra A90 by Pandem",
  "rmodz350pandem" : "Nissan 350z by Pandem",
  "rolls08" : "Rolls-Royce Sweptail",
  "rs3" : "Audi RS 3 II",
  "rmodrs6" : "Audi RS 6 Avant",
  "rs72" : "Audi RS 7",
  "s600" : "Mercedes-Benz S600 W140",
  "subie" : "Subaru Impreza WRX STi",
  "taycan" : "Porsche Taycan Turbo S",
  "umkscout" : "BMW X7 M60i",
  "v447" : "Mercedes-Benz Vito III",
  "volvoxc90" : "Volvo XC90",
  "w210" : "Mercedes-Benz E-Class W210",
  "w223" : "Mercedes-Benz S-Class W223",
  "yzfr6" : "Yamaha YZF-R6",
  "765ltmso" : "McLaren 765LT",
  "bc5506d" : "Ford F-550 Super Duty",
  "fpacel" : "Jaguar F-PACE",
  "octavia18" : "Skoda Octavia",
  "2020ss" : "Chevrolet Camaro SS",
  "bmwm4" : "BMW M4 Coupe",
  "dawn" : "Rolls-Royce Dawn",
  "f12berlinetta" : "Ferrari F12 Berlinetta",
  "f40" : "Ferrari F40",
  "f458" : "Ferrari F458 Italia",
  "geng90" : "Genesis G90",
  "GT17" : "Ford GT 2017",
  "modelx" : "Tesla Model X",
  "s1000rr" : "BMW S1000 RR",
  "cruzzz" : "Toyota Land Cruiser 300",
  "fenyr" : "W Motors Fenyr SuperSport",
  "mark2" : "Toyota Mark II",
  "ninjah2r" : "Kawasaki Ninja H2R",
  "roma" : "Ferrari Roma",
  "rx8r" : "Mazda RX-8",
  "sian" : "Lamborghini SIÁN FKP 37",
  "supra" : "Toyota Supra A80",
  "tesla" : "Tesla Model 3",
  "teslas" : "Tesla Model S",
  "190e": "Mercedes-Benz 190 Evo II",
  "370z16": "Nissan 370Z",
  "488pista": "Ferrari 488 Pista",
  "600lt": "McLaren 600LT",
  "benzc32": "Mercedes-Benz C32 AMG",
  "brabus700": "Brabus G63 AMG 6x6 B63S-700",
  "bugatticentodieci": "Bugatti Centodieci",
  "camaro": "Chevrolet Camaro SS",
  "cesc21": "Cadillac Escalade",
  "chiron17": "Bugatti Chiron",
  "63amg": "Mercedes-Benz G63 AMG",
  "eleanor": "Ford Mustang Shelby GT500 Eleanor",
  "golf7r": "Volkswagen Golf 7R",
  "lancer": "Mitsubishi Lancer Evolution X",
  "m5": "BMW M5",
  "m5e60": "BMW M5 E60",
  "techart": "Porsche Panamera Turbo",
  "wraith": "Rolls-Royce Wraith",
  "x5om": "BMW X5 M",
  "dbx": "Aston Martin DBX",
  "divo": "Bugatti Divo",
  "exige12": "Lotus Exige S",
  "f8t": "Ferrari F8 Tributo",
  "f812": "Ferrari 812 Superfast",
  "forgt50020": "Ford Mustang Shelby GT500 2020",
  "g63": "Mercedes-Benz G63 AMG",
  "gl450": "Mercedes-Benz GL450 4MATIC",
  "hevos": "Lamborghini Huracan Spyder",
  "jes": "Koenigsegg Jesko",
  "mbbs20": "Mercedes-Benz AMG GT RI",
  "modena99": "Ferrari 360 Modena",
  "panamera17turbo": "Porsche Panamera Turbo",
  "pgt2": "Porsche 911 GT2",
  "r820": "Audi R8",
  "rculi": "Rolls-Royce Cullinan",
  "rs62": "Audi RS 6 Avant",
  "svt00": "Ford Mustang SVT Cobra",
  "z48": "BMW Z4 M",
  "2013rs7": "Audi RS7",
  "bugatti": "Bugatti Veyron",
  "cam8tun": "Toyota Camry 3.5 AT XSE",
  "gt86": "Toyota GT86",
  "gtr": "Nissan GT-R",
  "lp700": "Lamborghini Aventador LP700-4",
  "m3e30": "BMW M3 E30",
  "sti": "Subaru Impreza WRX STi",

  //Тюнинг салон
  "rm3e36" : "rm3e36",
  "rmodamgc63" : "rmodamgc63",
  "rmodi8mlb" : "rmodi8mlb",
  "rmodfordgt" : "rmodfordgt",
  "rmodgtr" : "rmodgtr",
  "rmodlp750" : "rmodlp750",
  "rmodm3e36" : "rmodm3e36",
  "rmodm4" : "rmodm4",
  "rmodm4gts" : "rmodm4gts",
  "rmodmi8lb" : "rmodmi8lb",
  "rmodmustang" : "rmodmustang",
  "rmodrs7" : "rmodrs7",
  "rmodskyline" : "rmodskyline",
  "rmodsupra" : "rmodsupra",
  "rmodx6" : "rmodx6",






}

/* */
exports.get = function (value) { return RealCarNames[value] }
